# 插值

In [12]:
## 拉格朗日多项式插值
import numpy as np
from scipy.interpolate import lagrange

# 插值节点的x坐标和对应的y坐标
func = lambda x: np.exp(2 * x) * np.sin(3 * x)

x = np.array([0, 1, 2])
y = func(x)

print(f"y = {y}")

# 计算拉格朗日插值多项式
poly = lagrange(x, y)

# 输出多项式系数
print(poly)


y = [  0.           1.04274366 -15.25556929]
        2
-8.671 x + 9.713 x


In [13]:
from sympy import Symbol, exp, sin
from sympy.polys.polyfuncs import interpolate

# 定义插值节点
x_values = [0, 1, 2]

# 定义函数
x = Symbol('x')
f = exp(2*x) * sin(3*x)

# 计算 Lagrange 插值多项式
lagrange_poly = interpolate(x_values, [f.subs(x, xi) for xi in x_values])

# 获取高精度的系数
coefficients = lagrange_poly.all_coeffs()

# 输出多项式系数
print(coefficients)


KeyboardInterrupt: 

# 数值积分

## 梯形公式&Simpson 公式（大步长时注意包含右端点）

In [ ]:
import scipy
scipy.info(scipy.integrate.simpson)

 simpson(y, x=None, dx=1.0, axis=-1, even='avg')

Integrate y(x) using samples along the given axis and the composite
Simpson's rule. If x is None, spacing of dx is assumed.

If there are an even number of samples, N, then there are an odd
number of intervals (N-1), but Simpson's rule requires an even number
of intervals. The parameter 'even' controls how this is handled.

Parameters
----------
y : array_like
    Array to be integrated.
x : array_like, optional
    If given, the points at which `y` is sampled.
dx : float, optional
    Spacing of integration points along axis of `x`. Only used when
    `x` is None. Default is 1.
axis : int, optional
    Axis along which to integrate. Default is the last axis.
even : str {'avg', 'first', 'last'}, optional
    'avg' : Average two results:1) use the first N-2 intervals with
              a trapezoidal rule on the last interval and 2) use the last
              N-2 intervals with a trapezoidal rule on the first interval.

    'first' : Use 

/tmp/ipykernel_722/3339673506.py:2: DeprecationWarning: scipy.info is deprecated and will be removed in SciPy 2.0.0, use numpy.info instead
  scipy.info(scipy.integrate.simpson)


In [ ]:
import numpy as np
from scipy import integrate

# 被积函数
func = lambda theta: np.sqrt(1 - 0.15**2 * (np.sin(theta)**2))

# # 指定采样点数目
# for i in range(3,7): 
#     n = 10 ** i
#     xs = np.linspace(0.0, 1.0, n)
#     ys = func(xs)
#     integral_by_trapezoid = integrate.trapezoid(ys,xs) # 梯形公式
#     integral_by_simpson = integrate.simpson(ys,xs) # 辛普森公式

#     print(f"trapezoid formula :{integral_by_trapezoid:.15f} (n={n})")
#     print(f"Simpson formula   :{integral_by_simpson:.15f} (n={n})")

# 指定步长

def step_integral(func, start, stop, step, abs_err = 1e-15, rel_err = 1e-15):
    xs = np.arange(start, stop + 0.1 * step, step)
    ys = func(xs)
    precise_integral = integrate.quad(func, start, stop, epsabs=abs_err, epsrel=rel_err, )[0]
    integral_by_trapezoid = integrate.trapezoid(ys,xs) # 梯形公式
    
    xs = np.linspace(start, stop, 100000)
    ys = func(xs)
    integral_by_simpson = integrate.simpson(ys,xs) # 辛普森公式
    print(f"precise integral  : {precise_integral}")
    print(f"integral interval : [{start}, {stop}] (step={step})")
    print(f"trapezoid formula :{integral_by_trapezoid:.15f}")
    print(f"Simpson formula   :{integral_by_simpson:.15f}")
    
step_integral(func, 0 ,2 * np.pi, np.pi / 2)

precise integral  : 6.247691871606495
integral interval : [0, 6.283185307179586] (step=1.5707963267948966)
trapezoid formula :6.247641317417333
Simpson formula   :6.247691871606496


/tmp/ipykernel_4649/439458796.py:23: IntegrationWarning: The occurrence of roundoff error is detected, which prevents 
  the requested tolerance from being achieved.  The error may be 
  underestimated.
  precise_integral = integrate.quad(func, start, stop, epsabs=abs_err, epsrel=rel_err, )[0]


In [ ]:
import numpy as np


    

# 数值微分

In [ ]:
import numpy as np

def calculate_derivative(y, h):
    n = len(y)
    dy = [0] * n

    # 中间点的导数
    for i in range(1, n-1):
        dy[i] = (y[i+1] - y[i-1]) / (2 * h)

    # 左端点的导数（向前差分）
    dy[0] = (-3 * y[0] + 4 * y[1] - y[2]) / (2 * h)

    # 右端点的导数（向后差分）
    dy[n-1] = (3 * y[n-1] - 4 * y[n-2] + y[n-3]) / (2 * h)

    return dy


t = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
x = np.array([1070, 1270, 1480, 1700, 1910, 2140, 2360, 2600, 2830, 3070, 3310])
v = np.array([190, 200, 210, 216, 225, 228, 231, 234, 239, 240, 246])

a = calculate_derivative(v, 1)
print(f"a = {a}")



[10.0, 10.0, 8.0, 7.5, 6.0, 3.0, 3.0, 4.0, 3.0, 3.5, 8.5]


In [ ]:
import numpy as np
from scipy.optimize import least_squares

# 加载数据集，假设已经有了一组v(t)与t的数据
t_data = np.arange(10, 21, 1)
v_data = np.array([190, 200, 210, 216, 225, 228, 231, 234, 239, 240, 246])
assert len(t_data) == len(v_data)
a_data = np.zeros(len(t_data))
for i in range(1, len(t_data) - 1):
    a_data[i] = (v_data[i + 1] - v_data[i - 1]) / 2
a_data[0] = v_data[1] - v_data[0]
a_data[len(t_data) - 1] = v_data[len(t_data) - 1] - v_data[len(t_data) - 2]

print(a_data)

def objective(x):
    #! 构造残差函数，也即 f = g(t)，则残差为 f - g(t)
    k = x[0]
    F = np.zeros(len(t_data))
    for i in range(len(t_data)):
        v = v_data[i]
        a = a_data[i]
        t = t_data[i]
        m = 1200 -15 * t
        F[i] = a - (-k * v**2 / m + 40000 / m - 9.8)
    return F

x0 = [0.5]
#! x0 的选取影响很大，但是 tau 确实不该取 0
res = least_squares(objective, x0)
print(res.x)

def k_func(a, t, v):
    m = 1200 -15 * t
    k = (40000 - 9.8 * m - a * m) / v ** 2
    return k

k_list = []

for i in range(len(t_data)):
    k = k_func(a_data[i], t_data[i], v_data[i])
    k_list.append(k)

np.mean(k_list)

#! 上方采用了直接求均值法和最小二乘法

k_list.append(res.x[0])


def t_test(data_list, confidence_level, mu_0=None, test_method="double"):
    print("用于在方差未知的情况下估计均值或者对均值进行检验")
    assert test_method in ["left", "right", "double"]
    from scipy.stats import t
    import numpy as np
    n = len(data_list)
    sample_mean = np.mean(data_list)
    print("样本均值: ", sample_mean)
    sample_std = np.std(data_list, ddof=1)
    print("样本标准差: ", sample_std)
    center = mu_0 if mu_0 else sample_mean
    #! 假设检验需要传入假设的 mu_0，区间估计本身就是为了估计 mu_0，不用 mu_0
    if mu_0 != None:
        print("正在进行假设检验")
        t_statistic = (sample_mean - mu_0) / (sample_std / np.sqrt(n))
    else:
        print("正在进行区间估计")
    #! t_statistic 仅在计算 p 的时候使用，p 表示在 mu_0 正确时，sample_mean 比起当前更异常的概率
    if test_method == "double":
        print("正在计算双侧区间")
        #! alpha = 1 - confidence_level，故而 1 + confidence_level) / 2 = 1- alpha / 2
        t_value = t.ppf((1 + confidence_level) / 2, df=n - 1)
    else:
        print("正在计算单侧区间")
        t_value = t.ppf(confidence_level, df=n - 1)
    margin_error = t_value * sample_std / np.sqrt(n)
    lower_bound = center - margin_error
    upper_bound = center + margin_error
    if test_method == "double":
        #! 决定是否接受假设的时候，可以直接用 sample_mean 和 bound 比较，也可以用 t_statistic 和统计量（比如 u_{1- alpha / 2}）作对比
        print(f"Confidence Interval[{confidence_level}]:", lower_bound, "-", upper_bound)
        if mu_0 != None:
        #! p 和 confidence_level / alpha 没有任何关系，只有假设检验有 p 这个概念
            p_value = 2 * (1 - t.cdf(np.abs(t_statistic), df=n - 1))
    elif test_method == "right":
        #! 样本均值大于 right_bound 则拒绝假设
        print(f"Confidence Interval[{confidence_level}]:", "right_bound ", upper_bound)
        if mu_0 != None:
            p_value = 1 - t.cdf(t_statistic, df=n - 1)
    elif test_method == "left":
        #! 样本均值小于 left_bound 则拒绝假设
        print(f"Confidence Interval[{confidence_level}]:", "left_bound", lower_bound)
        if mu_0 != None:
            p_value = t.cdf(t_statistic, df=n - 1)
    if mu_0 != None:
        print(f"P-value: {p_value}")
        return p_value


t_test(k_list, 0.95, mu_0=0.5, test_method="double")

[10.  10.   8.   7.5  6.   3.   3.   4.   3.   3.5  6. ]
[0.48749859]
用于在方差未知的情况下估计均值或者对均值进行检验
样本均值:  0.492548210963488
样本标准差:  0.027646129207894426
正在进行假设检验
正在计算双侧区间
Confidence Interval[0.95]: 0.48243448752934703 - 0.517565512470653
P-value: 0.3704914113930142


0.3704914113930142

# 常微分方程初值问题

In [ ]:
import scipy

 solve_ivp(fun, t_span, y0, method='RK45', t_eval=None, dense_output=False,
           events=None, vectorized=False, args=None, **options)

Solve an initial value problem for a system of ODEs.

This function numerically integrates a system of ordinary differential
equations given an initial value::

    dy / dt = f(t, y)
    y(t0) = y0

Here t is a 1-D independent variable (time), y(t) is an
N-D vector-valued function (state), and an N-D
vector-valued function f(t, y) determines the differential equations.
The goal is to find y(t) approximately satisfying the differential
equations, given an initial value y(t0)=y0.

Some of the solvers support integration in the complex domain, but note
that for stiff ODE solvers, the right-hand side must be
complex-differentiable (satisfy Cauchy-Riemann equations [11]_).
To solve a problem in the complex domain, pass y0 with a complex data type.
Another option always available is to rewrite your problem for real and
imaginary parts separately.

Param

/tmp/ipykernel_1144/382934652.py:3: DeprecationWarning: scipy.info is deprecated and will be removed in SciPy 2.0.0, use numpy.info instead
  scipy.info(solve_ivp)


In [ ]:
scipy.info(scipy.integrate.solve_ivp)

## 向前欧拉法+改进欧拉法

In [15]:
import numpy as np

# 微分方程右侧函数 f
def f(t, y):
    return y + 2 * t

def forward_euler(h, t_end):
    t = np.arange(0, t_end + h, h)
    n = len(t)
    y = np.zeros(n)
    y[0] = 1

    for i in range(n-1):
        y[i+1] = y[i] + h * f(t[i], y[i])

    return t, y

def improved_euler(h, t_end):
    t = np.arange(0, t_end + h, h)
    n = len(t)
    y = np.zeros(n)
    y[0] = 1

    for i in range(n-1):
        y_expected = y[i] + h * f(t[i], y[i])
        y[i+1] = y[i] + h / 2 * (f(t[i], y[i]) + f(t[i+1], y_expected))
    return t, y

# 精确解
def exact_solution(t):
    return 3 * np.exp(t) - 2 * t - 2

h = 0.1
t_end = 1

# 向前欧拉法
t_forward, y_forward = forward_euler(h, t_end)
forward_euler_value = y_forward[-1]

# 改进欧拉法
t_improved, y_improved = improved_euler(h, t_end)
improved_euler_value = y_improved[-1]

# 精确解
t_exact = np.linspace(0, t_end, 100)
y_exact = exact_solution(t_exact)

# 误差分析
forward_euler_error = np.abs(forward_euler_value - exact_solution(t_end))
improved_euler_error = np.abs(improved_euler_value - exact_solution(t_end))

print("向前欧拉法得到的值为:", forward_euler_value)
print("改进欧拉法得到的值为:", improved_euler_value)
print("向前欧拉法精度的误差：", forward_euler_error)
print("改进欧拉法精度的误差:", improved_euler_error)


向前欧拉法得到的值为: 3.7812273803000007
改进欧拉法得到的值为: 4.142242539824673
向前欧拉法精度的误差： 0.373618105077135
改进欧拉法精度的误差: 0.01260294555246233


## 改进欧拉法

In [1]:
def improved_euler(f, y0 = 1, t0 = 0, h = 0.1, t_end = 1):
    t = np.arange(t0, t_end + 0.1 * h, h)
    n = len(t)
    y = np.zeros(n)
    y[0] = y0

    for i in range(n-1):
        y_expected = y[i] + h * f(t[i], y[i])
        y[i+1] = y[i] + h / 2 * (f(t[i], y[i]) + f(t[i+1], y_expected))
        print(t[i+1], y[i+1])
    return t, y

y0 = 1.6
t0 = 1
h = 0.2
t_end = 2

# 改进欧拉法
t_improved, y_improved = improved_euler(f, y0, t0, h, t_end)
print(f"t_improved = {t_improved}")
print(f"y_improved = {y_improved}")
improved_euler_value = y_improved[-1]
print(f"improved_euler_value = {improved_euler_value}")

NameError: name 'f' is not defined

## 一阶常微分线性方程

In [ ]:
import numpy as np
from scipy.integrate import solve_ivp

sol = solve_ivp(
        fun=lambda t, y: y ** 3 - np.exp(y) + t - 1,
        y0=[1.6],
        t_span=(1, 3),
        t_eval=[2],
        # dense_output=True
)

print(sol)
print(sol.y)

## 二阶及以上的常微分线性方程/常微分线性方程组

### `solve_ivp`

In [ ]:
import numpy as np
from scipy.integrate import solve_ivp

def ode_system(t, y):
    """
    Defines the system of ODEs to be solved.
    
    Parameters:
        t: float
            The current time point.
        y: array_like
            An array with shape (2,) containing the values of y at the current time point.
            
    Returns:
        dydt: array_like
            An array with shape (2,) containing the derivatives of y at the current time point.
    """
    y1, y2 = y[0], y[1]
    dydt = [f1(y1, y2, t), f2(y1, y2, t)]
    return dydt

# Define the functions f1 and f2
def f1(y1, y2, t):
    return y2
    
def f2(y1, y2, t):
    return - y2 / t + (1 / (4 * t ** 2) -1 ) * y1

# Solve the system of ODEs
t_span = (np.pi/2, 0)  # Time span to integrate over
y0 = [2, -2/np.pi]  # Initial conditions for y1 and y2
sol = solve_ivp(ode_system, t_span, y0, t_eval=[np.pi/6], first_step=0.0001, max_step=0.0001)

print(sol)



  message: Required step size is less than spacing between numbers.
  success: False
   status: -1
        t: [ 5.236e-01]
        y: [[ 1.732e+00]
            [ 1.346e+00]]
      sol: None
 t_events: None
 y_events: None
     nfev: 101455
     njev: 0
      nlu: 0


/tmp/ipykernel_1144/141343170.py:27: RuntimeWarning: divide by zero encountered in double_scalars
  return - y2 / t + (1 / (4 * t ** 2) -1 ) * y1
/tmp/ipykernel_1144/141343170.py:27: RuntimeWarning: invalid value encountered in double_scalars
  return - y2 / t + (1 / (4 * t ** 2) -1 ) * y1
/tmp/ipykernel_1144/141343170.py:27: RuntimeWarning: overflow encountered in double_scalars
  return - y2 / t + (1 / (4 * t ** 2) -1 ) * y1


### `odeint`

In [ ]:
import numpy as np
from scipy.integrate import odeint

def f(y, x):
    """
    定义二阶微分方程

    :param y: 因变量
    :param x: 自变量
    :return: 二阶微分方程的值
    """
    return [y[1], -(x * y[1] + (x ** 2 - 1/4) * y[0]) / (x ** 2)]

# 初始条件
y_a = [2, -2/np.pi]

# 自变量范围
x = np.linspace(np.pi/2, np.pi/6, 100)

# 求解微分方程
y, info = odeint(f, y_a, x, 
                #  full_output=True
                )

# 输出结果
print(round(y[-1, 0], 5))
print(info)

1.73205
{'hu': array([-0.00591995, -0.01889346, -0.01889346, -0.01565965, -0.01565965,
       -0.01565965, -0.01565965, -0.01565965, -0.01565965, -0.03131929,
       -0.03131929, -0.03131929, -0.03131929, -0.03131929, -0.03131929,
       -0.03131929, -0.03131929, -0.03131929, -0.03131929, -0.03131929,
       -0.03131929, -0.03131929, -0.03131929, -0.03131929, -0.04232654,
       -0.04232654, -0.04232654, -0.04232654, -0.04232654, -0.04232654,
       -0.04232654, -0.04232654, -0.04232654, -0.04232654, -0.04232654,
       -0.04232654, -0.04232654, -0.04232654, -0.04232654, -0.04232654,
       -0.04232654, -0.04232654, -0.04232654, -0.04232654, -0.04232654,
       -0.04232654, -0.04232654, -0.04232654, -0.04232654, -0.04232654,
       -0.04232654, -0.04232654, -0.04232654, -0.04232654, -0.04232654,
       -0.04232654, -0.04232654, -0.04232654, -0.04232654, -0.04232654,
       -0.03500456, -0.03500456, -0.03500456, -0.03500456, -0.03500456,
       -0.03500456, -0.03500456, -0.03500456, -0.

In [ ]:
import numpy as np
from scipy.integrate import odeint

def f(y, x):
    """
    定义二阶微分方程

    :param y: 因变量
    :param x: 自变量
    :return: 二阶微分方程的值
    """
    return [y[1], y[0] * np.sin(x)]

# 初始条件
y_a = [1, 0]

# 自变量范围
x = np.linspace(0, 1, 100)

# 求解微分方程
# y, info = odeint(f, y_a, x, full_output=True)
# print(info)


y = odeint(f, y_a, x, full_output=False)

# 输出结果
print(y[-1])

[1.16353624 0.48874799]


# 迭代法解非线性方程

## 一般的迭代法

In [ ]:
import math

def iteration_solve(x0, max_iter = 1000):
    tolerance = 1e-5  # 容许误差

    x_prev = x0
    x_next = math.acos(0.25 * x_prev + math.cos(3) + 0.75)
    iteration = 1

    while abs(x_next - x_prev) > tolerance and iteration < max_iter:
        x_prev = x_next
        x_next = math.acos(0.25 * x_prev + math.cos(3) + 0.75)
        iteration += 1

    root = x_next
    convergence_order = math.log(abs(root - x_prev)) / math.log(abs(x_prev - x0))

    print('Root:', root)
    print('Iterations:', iteration)
    print('Convergence order:', convergence_order)
    
    return root

x0 = 0.8

iteration_solve(x0)


Root: 1.4483860173257999
Iterations: 10
Convergence order: 29.129846147766315


1.4483860173257999

## 牛顿法

In [ ]:
import numpy as np
import scipy.integrate as spi
import matplotlib.pyplot as plt

def f(x):
    return np.cos(np.exp(3 / (x + 1))) * np.sin(2 * x)

def calculate_z(x):
    z = []
    for k in range(len(x)):
        integral, _ = spi.quad(f, 0, x[k])
        z.append(integral)
    return z

def plot_graph(x, z):
    plt.plot(x, z)
    plt.plot(x, [0.36] * len(x), 'r')
    plt.show()

def calculate_xx():
    xx = [2]
    for k in range(8):
        ff, _ = spi.quad(f, 0, xx[k])
        ff -= 0.36
        fd = np.cos(np.exp(3 / (xx[k] + 1))) * np.sin(2 * xx[k])
        xx.append(xx[k] - ff / fd)
    return xx[8]

x = np.arange(0, 10.1, 0.1)
z = calculate_z(x)
plot_graph(x, z)
result = calculate_xx()
print(result)


# 基本矩阵运算

## LU 分解

In [17]:
import numpy as np
from scipy.linalg import lu

A = np.array([[5, -1, -3], 
              [-1, 2, 4],
              [-3, 4, 15]])

P, L, U = lu(A)

print("P:", P)
print("L:", L)
print("U:", U)

P: [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
L: [[ 1.          0.          0.        ]
 [-0.6         1.          0.        ]
 [-0.2         0.52941176  1.        ]]
U: [[ 5.         -1.         -3.        ]
 [ 0.          3.4        13.2       ]
 [ 0.          0.         -3.58823529]]


## Cholesky 分解

In [20]:
import numpy as np

A = np.array([[5, -1, -3], [-1, 2, 4], [-3, 4, 15]])

U = np.linalg.cholesky(A)

x = np.linalg.solve(U.T, np.linalg.solve(U, b))

print("U =")
print(U)

U =
[[ 2.23606798  0.          0.        ]
 [-0.4472136   1.34164079  0.        ]
 [-1.34164079  2.53421037  2.60341656]]


# 线性方程组/矩阵方程求解

## 矩阵方程求解

In [ ]:
import numpy as np

A = np.array([[4, 2, -2], [1, 1, 1], [2, 2, 4]])
b = np.array([4, 2, 5])
x0 = np.array([1, 1, 1])

# 使用列主元Gauss消去法求解
x_gauss = np.linalg.solve(A, b)
cond_A = np.linalg.cond(A, 2)

print("使用列主元Gauss消去法求解得到 x =", x_gauss)
print("条件数Cond2(A) =", cond_A)
print("使用Gauss-Seidel迭代法求解5次得到 x(5) =", x_gs)



使用列主元Gauss消去法求解得到 x = [1.  0.5 0.5]
条件数Cond2(A) = 34.55112166226198
使用Gauss-Seidel迭代法求解5次得到 x(5) = [0 2 0]


In [ ]:
import numpy as np
from scipy.sparse import diags

n = 5
b = [0,0,2,4,0]
d = np.array([0.3,0.3,0.2,0.2])
s = 1 - d
h = [0, 400, 200, 150, 100]

L = diags([s], [-1]).toarray()
L[0,:] += b
neg_unit = diags([[-1 for _ in range(n)]], [0]).toarray()
A = L + neg_unit

print(A)

# A = diags(np.ones(n)).toarray()

x = np.linalg.solve(A, h)
print(x)

[[-1.   0.   2.   4.   0. ]
 [ 0.7 -1.   0.   0.   0. ]
 [ 0.   0.7 -1.   0.   0. ]
 [ 0.   0.   0.8 -1.   0. ]
 [ 0.   0.   0.   0.8 -1. ]]
[2000. 1000.  500.  250.  100.]


## 特征值

In [ ]:
np.linalg.eigvals(L)

array([ 0.        +0.j        ,  1.29818991+0.j        ,
       -0.19529393+1.13695161j, -0.19529393-1.13695161j,
       -0.90760204+0.j        ])

## 条件数

In [23]:
import numpy as np

order = 1

A=np.array([
    [5, -7, 0, 1],
    [-3,22,6,2],
    [5,-1,31,-1],
    [2,1,0,23]
])
b = np.array([6,3,4,7])
pert_b = np.array([0,0,0,0.1])

cond_A = np.linalg.cond(A, p=order)
print(cond_A)

rel_pert_b = np.linalg.norm(pert_b, ord=order) / np.linalg.norm(b, ord=order)
print(rel_pert_b)

sup_rel_err_x = cond_A * rel_pert_b
print(sup_rel_err_x)

14.867813041786082
0.005
0.07433906520893041


In [26]:
import numpy as np
from scipy.sparse import diags
order = 2
n = 50
diag = np.ones(50) * 2
subdiag = np.ones(49)
A = diags([subdiag, diag, subdiag] , [-1, 0, 1]).toarray()
# print(f"A = {A}")
cond_2_A = np.linalg.cond(A, p=order)
print(f"cond_2_A = {cond_2_A}")

cond_A = 1053.4789912002955


## 高斯-赛德尔迭代法（Gauss-Sedeil）

In [ ]:
def gauss_sedeil(A, b, x0, tol, max_iter, verbose = True):
    x = x0.copy()

    # 求 D_sub_L_inv
    D = np.diag(np.diag(A))
    U = -(np.triu(A) - D)
    L = -(np.tril(A) - D)
    D_sub_L_inv = np.linalg.inv(D - L)

    for i in range(max_iter):
        # print(f"x^({i}) = {x}")

        x_new = D_sub_L_inv @ (U @ x + b)
        err = np.linalg.norm(x_new - x)
        
        x = x_new
        if  err < tol:
            if verbose: print(f"Converge after {i+1} iterations")
            break
        
    if verbose:
        print(f"x^({i+1}) = {x}")
        print(f"relative error = {err}")
    return x, err

gauss_sedeil(A=A,b=b,x0=np.zeros(4),tol=1e-6,max_iter=5)

x^(5) = [ 1.71597235  0.39264682 -0.1305711   0.13806124]
relative error = 0.01541933644526515


(array([ 1.71597235,  0.39264682, -0.1305711 ,  0.13806124]),
 0.01541933644526515)

In [ ]:
gauss_sedeil(A=A,b=b,x0=np.zeros(4),tol=1e-6,max_iter=100)

Converge after 16 iterations
x^(16) = [ 1.72603719  0.3953224  -0.1321869   0.1370697 ]
relative error = 6.135494817040176e-07


(array([ 1.72603719,  0.3953224 , -0.1321869 ,  0.1370697 ]),
 6.135494817040176e-07)

谱半径

In [ ]:
def cal_B_G_S(A):
    """求 G-S 迭代的迭代矩阵""" 
    D = np.diag(np.diag(A))
    U = -(np.triu(A) - D)
    L = -(np.tril(A) - D)
    D_sub_L_inv = np.linalg.inv(D - L)
    B_G_S = D_sub_L_inv @ U 
    
    return B_G_S

B_G_S = cal_B_G_S(A)
# print(B_G_S)
# 求 B_G_S 的谱半径
rho_B_G_S = np.max(np.abs(np.linalg.eigvals(B_G_S)))
print(rho_B_G_S)

In [31]:
import numpy as np
from scipy.sparse import diags

def cal_B_G_S(A):
    """求 G-S 迭代的迭代矩阵""" 
    D = np.diag(np.diag(A))
    U = -(np.triu(A) - D)
    L = -(np.tril(A) - D)
    D_sub_L_inv = np.linalg.inv(D - L)
    B_G_S = D_sub_L_inv @ U 
    
    return B_G_S

order = 2
n = 50
diag = np.ones(50) * 2
subdiag = np.ones(49)
A = diags([subdiag, diag, subdiag] , [-1, 0, 1]).toarray()


B_G_S = cal_B_G_S(A)
# print(B_G_S)
# 求 B_G_S 的谱半径
rho_B_G_S = np.max(np.abs(np.linalg.eigvals(B_G_S)))
print(f"rho_B_G_S = {rho_B_G_S}")

rho_B_G_S = 0.9962102548359681


# 最小二乘法

In [ ]:
import scipy
scipy.info(scipy.optimize.least_squares)

 least_squares(fun, x0, jac='2-point', bounds=(-inf, inf), method='trf',
               ftol=1e-08, xtol=1e-08, gtol=1e-08, x_scale=1.0, loss='linear',
               f_scale=1.0, diff_step=None, tr_solver=None, tr_options={},
               jac_sparsity=None, max_nfev=None, verbose=0, args=(),
               kwargs={})

Solve a nonlinear least-squares problem with bounds on the variables.

Given the residuals f(x) (an m-D real function of n real
variables) and the loss function rho(s) (a scalar function), `least_squares`
finds a local minimum of the cost function F(x)::

    minimize F(x) = 0.5 * sum(rho(f_i(x)**2), i = 0, ..., m - 1)
    subject to lb <= x <= ub

The purpose of the loss function rho(s) is to reduce the influence of
outliers on the solution.

Parameters
----------
fun : callable
    Function which computes the vector of residuals, with the signature
    ``fun(x, *args, **kwargs)``, i.e., the minimization proceeds with
    respect to its first argument. The argument ``

/tmp/ipykernel_4649/3432953689.py:2: DeprecationWarning: scipy.info is deprecated and will be removed in SciPy 2.0.0, use numpy.info instead
  scipy.info(scipy.optimize.least_squares)


## 线性最小二乘法+多项式拟合

In [ ]:
import numpy as np

# 实验数据
t = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])
y = np.array([4.00, 6.40, 8.00, 8.80, 9.22, 9.50, 9.70, 9.86, 10.00, 10.20, 10.32, 10.42, 10.50, 10.55, 10.58, 10.60])

# 二次多项式拟合
n = 2  # 多项式的阶数
A = np.vander(t, n + 1)  # 构建 Vandermonde 矩阵

print(f"A = {A}")

coefficients, residuals, _, _ = np.linalg.lstsq(A, y, rcond=None)

# 残差平方和
Q = residuals[0]

# 输出二次多项式拟合函数和残差平方和
print("二次多项式拟合函数：y =", end=" ")
for i in range(n + 1):
    print(f"{coefficients[i]:.4f} * t^{n - i}", end=" " if i < n else "\n")
print("拟合的残差平方和：", Q)

# 三次多项式拟合（经过坐标原点）
A = np.multiply(A, t[:, np.newaxis])  # 将矩阵的每一列与向量 t 对应元素相乘

print(f"A = {A}")

coefficients, residuals, _, _ = np.linalg.lstsq(A, y, rcond=None)

# 输出经过坐标原点的三次多项式拟合函数
print("经过坐标原点的三次多项式拟合函数：y =", end=" ")
for i in range(n + 1):
    print(f"{coefficients[i]:.4f} * t^{n - i + 1}", end=" " if i < n else "\n")


A = [[  1   1   1]
 [  4   2   1]
 [  9   3   1]
 [ 16   4   1]
 [ 25   5   1]
 [ 36   6   1]
 [ 49   7   1]
 [ 64   8   1]
 [ 81   9   1]
 [100  10   1]
 [121  11   1]
 [144  12   1]
 [169  13   1]
 [196  14   1]
 [225  15   1]
 [256  16   1]]
二次多项式拟合函数：y = -0.0445 * t^2 1.0660 * t^1 4.3875 * t^0
拟合的残差平方和： 4.907064499299699
A = [[   1    1    1]
 [   8    4    2]
 [  27    9    3]
 [  64   16    4]
 [ 125   25    5]
 [ 216   36    6]
 [ 343   49    7]
 [ 512   64    8]
 [ 729   81    9]
 [1000  100   10]
 [1331  121   11]
 [1728  144   12]
 [2197  169   13]
 [2744  196   14]
 [3375  225   15]
 [4096  256   16]]
经过坐标原点的三次多项式拟合函数：y = 0.0112 * t^3 -0.3440 * t^2 3.3419 * t^1


## 线性化

In [ ]:
import numpy as np
from scipy.optimize import curve_fit

t_data = np.array([0.3, 0.5, 1.0, 2.0, 4.0, 7.0])
v_data = np.array([5.6873, 6.1434, 7.1633, 8.8626, 11.0328, 12.6962])

log_v_data = np.log(14 - v_data)

def v_func(t, tau, v0):
    return np.log(14-v0) - t / tau

popt, pcov = curve_fit(v_func, t_data, log_v_data, p0=[1, 0])

tau = popt[0]
v0 = popt[1]


# 模板二

import numpy as np
from scipy.optimize import least_squares

list_t = np.array([0.3, 0.5, 1.0, 2.0, 4.0, 7.0])
v_data = np.array([5.6873, 6.1434, 7.1633, 8.8626, 11.0328, 12.6962])

def objective(x):
    v0 = x[0]
    tao = x[1]
    v = 14
    F = np.zeros(len(list_t))
    for i in range(len(list_t)):
        t = list_t[i]
        vt = v_data[i]
        F[i] = np.log(v -vt) - np.log(v - v0) + t / tao
    return F

x0 = [1, 1]
#! x0 的选取影响很大，但是 tau 确实不该取 0
res = least_squares(objective, x0)
print(res.x)

[5.00010907 3.61647546]


# 线性规划

In [ ]:
import scipy
scipy.info(linprog)

 linprog(c, A_ub=None, b_ub=None, A_eq=None, b_eq=None, bounds=None,
         method='highs', callback=None, options=None, x0=None,
         integrality=None)

Linear programming: minimize a linear objective function subject to linear
equality and inequality constraints.

Linear programming solves problems of the following form:

.. math::

    \min_x \ & c^T x \\
    \mbox{such that} \ & A_{ub} x \leq b_{ub},\\
    & A_{eq} x = b_{eq},\\
    & l \leq x \leq u ,

where :math:`x` is a vector of decision variables; :math:`c`,
:math:`b_{ub}`, :math:`b_{eq}`, :math:`l`, and :math:`u` are vectors; and
:math:`A_{ub}` and :math:`A_{eq}` are matrices.

Alternatively, that's:

minimize::

    c @ x

such that::

    A_ub @ x <= b_ub
    A_eq @ x == b_eq
    lb <= x <= ub

Note that by default ``lb = 0`` and ``ub = None`` unless specified with
``bounds``.

Parameters
----------
c : 1-D array
    The coefficients of the linear objective function to be minimized.
A_ub : 2-D array, optional
    The

/tmp/ipykernel_722/2196696522.py:2: DeprecationWarning: scipy.info is deprecated and will be removed in SciPy 2.0.0, use numpy.info instead
  scipy.info(linprog)


In [ ]:
import numpy as np
from scipy.optimize import linprog

# Define the objective function
c = np.array([-64, -54])

# Define the inequality constraints
A_ub = np.array([[3, 0], [12, 8]])
b_ub = np.array([80, 480])

# Define the equality constraints
A_eq = np.array([[1, 1]])
b_eq = np.array([55])

# Define the bounds
bounds = [(0, 55), (0, 55)]

# Call the linprog function
res = linprog(c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, bounds=bounds)

print(res)

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: -3070.0
              x: [ 1.000e+01  4.500e+01]
            nit: 0
          lower:  residual: [ 1.000e+01  4.500e+01]
                 marginals: [ 0.000e+00  0.000e+00]
          upper:  residual: [ 4.500e+01  1.000e+01]
                 marginals: [ 0.000e+00  0.000e+00]
          eqlin:  residual: [ 0.000e+00]
                 marginals: [-3.400e+01]
        ineqlin:  residual: [ 5.000e+01  0.000e+00]
                 marginals: [-0.000e+00 -2.500e+00]
 mip_node_count: 0
 mip_dual_bound: 0.0
        mip_gap: 0.0


In [ ]:
import numpy as np
from scipy.optimize import linprog

# 目标函数系数
c = np.array([1000, 1100, 850, 1000])

# 不等式约束矩阵和右侧常数
A = np.array([
    [5, 4, 0, 0],
    [0, 0, 2, 5]
])
b_ub = np.array([200 * 40, 120 * 20])

# 等式约束矩阵和右侧常数
A_eq = np.array([[1, 0, 1, 0], [0, 1, 0, 1]])
b_eq = np.array([1000, 1600])

# 变量取值范围
x_bounds = [(0, None), (0, None), (0, None), (0, None)]

# 使用线性规划求解
result = linprog(c, A_ub=A, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, bounds=x_bounds, method='highs')

# 输出结果
print("最小总成本:", result.fun)
print("甲饮料厂生产A饮料:", result.x[0], "t")
print("甲饮料厂生产B饮料:", result.x[1], "t")
print("乙饮料厂生产A饮料:", result.x[2], "t")
print("乙饮料厂生产B饮料:", result.x[3], "t")


最小总成本: 2602000.0
甲饮料厂生产A饮料: 0.0 t
甲饮料厂生产B饮料: 1520.0 t
乙饮料厂生产A饮料: 1000.0 t
乙饮料厂生产B饮料: 80.0 t


## 变量置为常数

In [ ]:
# 此处去掉 x_3
import numpy as np
from scipy.optimize import linprog

# 目标函数系数
# c = np.array([1000, 1100, 850, 1000])

c = np.array([1000, 1100, 1000])


# 不等式约束矩阵和右侧常数
# A = np.array([
#     [5, 4, 0, 0],
#     [0, 0, 2, 5]
# ])

A = np.array([
    [5, 4, 0],
    [0, 0, 5]
])

b_ub = np.array([200 * 40, 120 * 20])

# 等式约束矩阵和右侧常数
# A_eq = np.array([[1, 0, 1, 0], [0, 1, 0, 1]])

A_eq = np.array([[1, 0, 0], [0, 1, 1]])

b_eq = np.array([1000, 1600])

# 变量取值范围
# x_bounds = [(0, None), (0, None), (0, None), (0, None)]
x_bounds = [(0, None), (0, None), (0, None)]


# 使用线性规划求解
result = linprog(c, A_ub=A, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, bounds=x_bounds, method='highs')

print(result)

# 输出结果
print("最小总成本:", result.fun)
print("甲饮料厂生产A饮料:", result.x[0], "t")
print("甲饮料厂生产B饮料:", result.x[1], "t")
# print("乙饮料厂生产A饮料:", result.x[2], "t")
print("乙饮料厂生产B饮料:", result.x[2], "t")


       message: The problem is infeasible. (HiGHS Status 8: model_status is Infeasible; primal_status is At lower/fixed bound)
       success: False
        status: 2
           fun: None
             x: None
           nit: 0
         lower:  residual: None
                marginals: None
         upper:  residual: None
                marginals: None
         eqlin:  residual: None
                marginals: None
       ineqlin:  residual: None
                marginals: None
最小总成本: None


TypeError: 'NoneType' object is not subscriptable

## 添加约束

### 添加变量约束

In [ ]:
# 此处去掉 x_4，并添加变量约束 x_3 >= 300
import numpy as np
from scipy.optimize import linprog

# 目标函数系数
# c = np.array([1000, 1100, 850, 1000])

c = np.array([1000, 1100, 850])


# 不等式约束矩阵和右侧常数
# A = np.array([
#     [5, 4, 0, 0],
#     [0, 0, 2, 5]
# ])

A = np.array([
    [5, 4, 0],
    [0, 0, 2],
])

b_ub = np.array([200 * 40, 120 * 20])

# 等式约束矩阵和右侧常数
# A_eq = np.array([[1, 0, 1, 0], [0, 1, 0, 1]])

A_eq = np.array([[1, 0, 1], [0, 1, 0]])

b_eq = np.array([1000, 1600])

# 变量取值范围
# x_bounds = [(0, None), (0, None), (0, None), (0, None)]
x_bounds = [(0, None), (0, None), (300, None)]


# 使用线性规划求解
result = linprog(c, A_ub=A, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, bounds=x_bounds, method='highs')

print(result)

# 输出结果
print("最小总成本:", result.fun)
print("甲饮料厂生产A饮料:", result.x[0], "t")
print("甲饮料厂生产B饮料:", result.x[1], "t")
print("乙饮料厂生产A饮料:", result.x[2], "t")
# print("乙饮料厂生产B饮料:", result.x[2], "t")

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: 2610000.0
              x: [ 0.000e+00  1.600e+03  1.000e+03]
            nit: 0
          lower:  residual: [ 0.000e+00  1.600e+03  7.000e+02]
                 marginals: [ 1.500e+02  0.000e+00  0.000e+00]
          upper:  residual: [       inf        inf        inf]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00]
          eqlin:  residual: [ 0.000e+00  0.000e+00]
                 marginals: [ 8.500e+02  1.100e+03]
        ineqlin:  residual: [ 1.600e+03  4.000e+02]
                 marginals: [-0.000e+00 -0.000e+00]
 mip_node_count: 0
 mip_dual_bound: 0.0
        mip_gap: 0.0
最小总成本: 2610000.0
甲饮料厂生产A饮料: 0.0 t
甲饮料厂生产B饮料: 1600.0 t
乙饮料厂生产A饮料: 1000.0 t


In [ ]:
# 此处仅添加约束 x_3, x_4 >= 300
import numpy as np
from scipy.optimize import linprog

# 目标函数系数
c = np.array([1000, 1100, 850, 1000])

# 不等式约束矩阵和右侧常数
A = np.array([
    [5, 4, 0, 0],
    [0, 0, 2, 5]
])
b_ub = np.array([200 * 40, 120 * 20])

# 等式约束矩阵和右侧常数
A_eq = np.array([[1, 0, 1, 0], [0, 1, 0, 1]])
b_eq = np.array([1000, 1600])

# 变量取值范围
x_bounds = [(0, None), (0, None), (300, None), (300, None)]

# 使用线性规划求解
result = linprog(c, A_ub=A, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, bounds=x_bounds, method='highs')

# 输出结果
print("最小总成本:", result.fun)
print("甲饮料厂生产A饮料:", result.x[0], "t")
print("甲饮料厂生产B饮料:", result.x[1], "t")
print("乙饮料厂生产A饮料:", result.x[2], "t")
print("乙饮料厂生产B饮料:", result.x[3], "t")


最小总成本: 2662500.0
甲饮料厂生产A饮料: 550.0 t
甲饮料厂生产B饮料: 1300.0 t
乙饮料厂生产A饮料: 450.0 t
乙饮料厂生产B饮料: 300.0 t


# 基本数据分析

## 概率计算

In [ ]:
import numpy as np
from scipy import stats
from scipy.stats import chi2, norm

# 问题1
mu = 12
sigma = 1.2
prob_lt_10 = stats.norm.cdf(10, mu, sigma)
prob_gt_15 = 1 - stats.norm.cdf(15, mu, sigma)
ratio = prob_lt_10 + prob_gt_15
print("长度不超过10cm或超过15cm的金属棒的比例为:", ratio)

# 问题2
lower_bound, upper_bound = stats.norm.interval(0.93, mu, sigma)
print("金属棒长度以93%的可能性落入的最小区间是:", lower_bound, "cm到", upper_bound, "cm")


长度不超过10cm或超过15cm的金属棒的比例为: 0.05400001759859086
金属棒长度以93%的可能性落入的最小区间是: 9.825707192456882 cm到 14.174292807543118 cm
问题3：在显著性水平 alpha=0.05 时，这批金属棒长度的标准差是否为 1.2 cm?
样本标准差：1.6659 cm
卡方统计量：26.9815
临界值：23.6848
判断结果：拒绝

问题4：在显著性水平 alpha=0.05 时，利用样本数据检验这批金属棒长度的均值是否为 12 cm?
样本均值：12.3327 cm
标准误差：0.3098
z统计量：1.0737
临界值：1.6449
判断结果：接受


# 随机模拟(蒙特卡洛方法)求积分（建议精度尽可能大）

## 二维正态分布落入椭圆

In [ ]:
import numpy as np
from scipy.integrate import dblquad
from scipy.stats import multivariate_normal, pearsonr


def random_points(num_samples, mean, cov_matrix, a: float, b: float):
    """随机投点法"""
    # 投点
    random_points = np.random.multivariate_normal(mean, cov_matrix, num_samples)
    # 计算概率
    probability_point = (
        np.count_nonzero(
            random_points[:, 0] ** 2 / (a ** 2) + random_points[:, 1] ** 2 / (b ** 2) <= 1
        )
        / num_samples
    )
    return probability_point


def mean_estimate(num_samples: int, mean, cov_matrix, a: float, b: float) -> float:
    """均值估计法"""
    uniform_samples = np.random.uniform(
        low=[-a, -b],
        high=[a, b],
        size=(num_samples, 2),
    )
    pdf = multivariate_normal.pdf(uniform_samples, mean=mean, cov=cov_matrix)

    in_domain = np.where(
        uniform_samples[:, 0] ** 2 / (a ** 2) + uniform_samples[:, 1] ** 2 / (b ** 2) <= 1
    )[0]

    probability_mean = (4 * a * b) * np.sum(pdf[in_domain]) / num_samples
    return probability_mean


data_X = [-6.3, -71.6, 65.6, -79.2, -49.7, -81.9, 74.6, -47.6, -120.8, 56.9,
          100.9, 47, 9.7, -60.1, -52.7, 86, 80.6, -42.6, 56.4, 15.2]

data_Y = [28.9, 1.6, 61.7, -68, -41.3, -30.5, 87, 17.3, -17.8, 1.2,
          -12.6, 39.1, 85, 32.7, 28.1, -9.3, -4.5, 5.1, -32, -9.5]

corr, p_corr = pearsonr(data_X, data_Y)
print(corr, p_corr)

num_samples = 10000
mean = [0, 0]
sigma_x = 70
sigma_y = 50
cov_matrix = [[sigma_x ** 2, corr * sigma_x * sigma_y],
              [corr * sigma_x * sigma_y, sigma_y ** 2]]
a = 110
b = 90

print(random_points(num_samples, mean, cov_matrix, a, b))
print(mean_estimate(num_samples, mean, cov_matrix, a, b))



0.31303947939486954 0.17898652036430282
0.7572
0.7549063820107622


# 参数估计（点估计与区间估计）

## 相关系数

In [ ]:
import numpy as np
from scipy.stats import pearsonr

# 生成两个随机变量的样本数据
x = np.random.rand(100)
y = np.random.rand(100)

# 计算相关系数
corr_coef, p_value = pearsonr(x, y)

# 打印相关系数和p值
print("相关系数:", corr_coef)
print("p值:", p_value)


## 方差已知时均值的估计——z 估计

In [ ]:
import numpy as np
from scipy.stats import norm

norm(loc=16.4, scale=np.sqrt(5.4)).interval(confidence=0.95)

(5.816194483483706, 26.98380551651629)

## 方差未知时均值的估计——t 估计

In [ ]:
import scipy.stats as stats
import numpy as np

# 定义样本数据
sample = np.array([4, 3, 5, 6, 2, 4, 5, 3, 4, 5])

# 计算样本均值和样本标准差
sample_mean = np.mean(sample)
sample_std = np.std(sample, ddof=1)  # 使用Bessel's correction，自由度为n-1

# 设置置信水平和样本大小
confidence_level = 0.95
sample_size = len(sample)

# 计算t分布的临界值
t_critical = stats.t.ppf((1 + confidence_level) / 2, df=sample_size - 1)

# 计算置信区间的边界
margin_of_error = t_critical * sample_std / np.sqrt(sample_size)
confidence_interval = (sample_mean - margin_of_error, sample_mean + margin_of_error)

print("置信区间:", confidence_interval)


In [ ]:
import numpy as np
from scipy.stats import t

df = 25 - 1

t_dist = t(df)

t_dist.interval(confidence=0.95, loc=16.4, scale=np.sqrt(5.4/df))

# t_interval = np.array([t_dist.ppf(q=0.025), t_dist.ppf(q=0.975)])

# mu_interval = 16.4 + np.sqrt(5.4) * t_interval

# print(f"mu_interval = {mu_interval}")


(15.421006952856507, 17.37899304714349)

# 假设检验

## 均值的假设检验

### 方差已知时均值的假设检验——z 检验

In [ ]:
import numpy as np
from scipy.stats import norm

def ztest(data, mean_value, variance):
    """
    基于正态统计量进行一维数据均值双侧检验（在方差已知的情况下）

    参数：
    - data: 一维数组，表示观察值
    - mean_value: 指定的均值值
    - variance: 已知的方差值

    返回值：
    - statistic: 均值检验的统计值
    - p_value: 均值检验的p值

    """

    # 计算样本均值
    sample_mean = np.mean(data)

    # 计算样本大小
    sample_size = len(data)

    # 计算标准误差
    standard_error = np.sqrt(variance / sample_size)

    # 计算正态统计量
    z_statistic = (sample_mean - mean_value) / standard_error

    # 计算p值
    p_value = 2 * (1 - norm.cdf(np.abs(z_statistic)))

    result = (z_statistic, p_value)
    print(result)
    return result

data_X = [-6.3, -71.6, 65.6, -79.2, -49.7, -81.9, 74.6, -47.6, -120.8, 56.9,
          100.9, 47, 9.7, -60.1, -52.7, 86, 80.6, -42.6, 56.4, 15.2]

data_Y = [28.9, 1.6, 61.7, -68, -41.3, -30.5, 87, 17.3, -17.8, 1.2,
          -12.6, 39.1, 85, 32.7, 28.1, -9.3, -4.5, 5.1, -32, -9.5]

ztest(data_X, 0, 70 ** 2)
ztest(data_Y, 0, 50 ** 2)

(-0.06260990336999409, 0.9500771431429442)
(0.7253804519009317, 0.46821866210685026)


(0.7253804519009317, 0.46821866210685026)

In [ ]:
import numpy as np
from scipy.stats import norm

def ztest(data, mean_value, variance):
    """
    基于正态统计量进行一维数据均值双侧检验（在方差已知的情况下）

    参数：
    - data: 一维数组，表示观察值
    - mean_value: 指定的均值值
    - variance: 已知的方差值

    返回值：
    - statistic: 均值检验的统计值
    - p_value: 均值检验的p值

    """

    # 计算样本均值
    sample_mean = np.mean(data)

    # 计算样本大小
    sample_size = len(data)

    # 计算标准误差
    standard_error = np.sqrt(variance / sample_size)

    # 计算正态统计量
    z_statistic = (sample_mean - mean_value) / standard_error

    # 计算p值
    p_value = 2 * (1 - norm.cdf(np.abs(z_statistic)))

    result = (z_statistic, p_value)
    print(result)
    return result

lengths = np.array([11.10, 12.43, 12.57, 14.50, 10.84, 14.10, 11.98, 9.88, 12.05, 13.00, 14.00, 13.00, 12.09, 8.85, 14.60])

ztest(lengths, 12, 1.2 ** 2)

(1.073677049865272, 0.28296745092979125)


(1.073677049865272, 0.28296745092979125)

### 方差未知时均值的假设检验——t 检验

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import normaltest, ttest_1samp

data_X = [-6.3, -71.6, 65.6, -79.2, -49.7, -81.9, 74.6, -47.6, -120.8, 56.9,
          100.9, 47, 9.7, -60.1, -52.7, 86, 80.6, -42.6, 56.4, 15.2]

data_Y = [28.9, 1.6, 61.7, -68, -41.3, -30.5, 87, 17.3, -17.8, 1.2,
          -12.6, 39.1, 85, 32.7, 28.1, -9.3, -4.5, 5.1, -32, -9.5]

# 对 data_X 进行正态性检验
print("data_X 正态性检验结果:")
statistic_X, pvalue_X = normaltest(data_X)
print("统计量:", statistic_X)
print("p值:", pvalue_X)

# 对 data_X 进行单样本 t 检验
print("data_X 单样本 t 检验结果:")
tstat_X, pvalue_X = ttest_1samp(data_X, popmean=0)
print("t 统计量:", tstat_X)
print("p值:", pvalue_X)

# 对 data_Y 进行正态性检验
print("data_Y 正态性检验结果:")
statistic_Y, pvalue_Y = normaltest(data_Y)
print("统计量:", statistic_Y)
print("p值:", pvalue_Y)

# 对 data_Y 进行单样本 t 检验
print("data_Y 单样本 t 检验结果:")
tstat_Y, pvalue_Y = ttest_1samp(data_Y, popmean=0)
print("t 统计量:", tstat_Y)
print("p值:", pvalue_Y)

data_X 正态性检验结果:
统计量: 5.522304623532256
p值: 0.06321887851423949
data_X 单样本 t 检验结果:
t 统计量: -0.0641967753272205
p值: 0.9494841563760554
data_Y 正态性检验结果:
统计量: 0.7039336514839094
p值: 0.7033034531595805
data_Y 单样本 t 检验结果:
t 统计量: 0.9009033536206252
p值: 0.37891779962953087


In [ ]:
import numpy as np
from scipy.stats import ttest_1samp

def ttest_1samp_verbose(data, popmean):
    print("data 单样本 t 检验:")
    tstat, pvalue = ttest_1samp(data, popmean=popmean)
    print("t 统计量:", tstat)
    print("p值:", pvalue)
    
lengths = np.array([11.10, 12.43, 12.57, 14.50, 10.84, 14.10, 11.98, 9.88, 12.05, 13.00, 14.00, 13.00, 12.09, 8.85, 14.60])

ttest_1samp_verbose(lengths, 12)

data 单样本 t 检验:
t 统计量: 0.7734015096597734
p值: 0.4521467128196962


## 单总体方差的假设检验——卡方检验

In [ ]:
import numpy as np
from scipy.stats import chi2

def variance_test(data, expected_variance, alpha=0.05):
    """
    基于卡方分布统计量进行一维数据方差双侧检验

    参数：
    - data: 一维数组，表示观察值
    - variance_value: 指定的方差值

    返回值：
    - statistic: 方差检验的统计值
    - p_value: 方差检验的p值

    """

    # 计算样本方差
    sample_variance = np.var(data, ddof=1)

    # 计算样本大小
    sample_size = len(data)
    
    # 计算自由度
    df = sample_size - 1

    # 计算卡方统计量
    chi2_statistic = df * sample_variance / expected_variance


    # 计算p值
    if chi2_statistic > df:
        prob_extreme = 1 - chi2.cdf(np.abs(chi2_statistic), df)
    else:
        prob_extreme = chi2.cdf(np.abs(chi2_statistic), df)
    
    p_value = 2 * prob_extreme

    result = (chi2_statistic, p_value)
    print(result)
    
    # 计算样本均值
    sample_mean = np.mean(data)
    # 计算样本标准差
    sample_sigma = np.std(data, ddof=1)
    
    # acceptance_region = chi2.interval(confidence=1-alpha, df=df, loc=sample_mean, scale=sample_sigma)
    
    chi2_acceptance_region = chi2.interval(confidence=1-alpha, df=df)
    variance_acceptance_region = (df * sample_variance / chi2_acceptance_region[1], df * sample_variance / chi2_acceptance_region[0])
    
    # print(f"acceptance_region: {acceptance_region}")
    print(f"chi2_acceptance_region = {chi2_acceptance_region}")
    print(f"variance_acceptance_region = {variance_acceptance_region}")
    
    return result

data_X = [-6.3, -71.6, 65.6, -79.2, -49.7, -81.9, 74.6, -47.6, -120.8, 56.9,
          100.9, 47, 9.7, -60.1, -52.7, 86, 80.6, -42.6, 56.4, 15.2]

data_Y = [28.9, 1.6, 61.7, -68, -41.3, -30.5, 87, 17.3, -17.8, 1.2,
          -12.6, 39.1, 85, 32.7, 28.1, -9.3, -4.5, 5.1, -32, -9.5]


sigma_0_X = 70
sigma_0_Y = 50

var_0_X = sigma_0_X ** 2
var_0_Y = sigma_0_Y ** 2

variance_test(data_X, var_0_X);
variance_test(data_Y, var_0_Y);

(18.072292244897962, 0.964771596966736)
chi2_acceptance_region = (8.906516481987973, 32.85232686172969)
variance_acceptance_region = (2695.5238931084223, 9942.633820875648)
(12.317679199999999, 0.2567980414388543)
chi2_acceptance_region = (8.906516481987973, 32.85232686172969)
variance_acceptance_region = (937.3521129753749, 3457.4907105686507)


In [ ]:
import numpy as np
from scipy.stats import chi2

def variance_test(data, expected_variance, alpha=0.05):
    """
    基于卡方分布统计量进行一维数据方差双侧检验

    参数：
    - data: 一维数组，表示观察值
    - variance_value: 指定的方差值

    返回值：
    - statistic: 方差检验的统计值
    - p_value: 方差检验的p值

    """

    # 计算样本方差
    sample_variance = np.var(data, ddof=1)

    # 计算样本大小
    sample_size = len(data)
    
    # 计算自由度
    df = sample_size - 1

    # 计算卡方统计量
    chi2_statistic = df * sample_variance / expected_variance


    # 计算p值
    if chi2_statistic > df:
        prob_extreme = 1 - chi2.cdf(np.abs(chi2_statistic), df)
    else:
        prob_extreme = chi2.cdf(np.abs(chi2_statistic), df)
    
    p_value = 2 * prob_extreme

    result = (chi2_statistic, p_value)
    print(result)
    
    # 计算样本均值
    sample_mean = np.mean(data)
    # 计算样本标准差
    sample_sigma = np.std(data, ddof=1)
    
    # acceptance_region = chi2.interval(confidence=1-alpha, df=df, loc=sample_mean, scale=sample_sigma)
    
    chi2_acceptance_region = chi2.interval(confidence=1-alpha, df=df)
    variance_acceptance_region = (df * sample_variance / chi2_acceptance_region[1], df * sample_variance / chi2_acceptance_region[0])
    
    # print(f"acceptance_region: {acceptance_region}")
    print(f"chi2_acceptance_region = {chi2_acceptance_region}")
    print(f"variance_acceptance_region = {variance_acceptance_region}")
    
    return result

lengths = np.array([11.10, 12.43, 12.57, 14.50, 10.84, 14.10, 11.98, 9.88, 12.05, 13.00, 14.00, 13.00, 12.09, 8.85, 14.60])

variance_test(lengths, 1.2 ** 2, alpha=0.05)

(26.981453703703703, 0.03872156413704042)
chi2_acceptance_region = (5.628726103039734, 26.11894804503737)
variance_acceptance_region = (1.487551997359844, 6.902679686679197)


(26.981453703703703, 0.03872156413704042)

### 迷之检验

In [ ]:
import numpy as np
from scipy.stats import chi2

def variance_test(data, alpha):
    """
    基于卡方分布统计量进行方差检验

    参数：
    - data: 包含多个样本的二维数组，每一行是一个样本的观察值
    - alpha: 显著性水平

    返回值：
    - result: 布尔值，True表示拒绝原假设，即样本的方差存在显著差异；False表示无法拒绝原假设

    """

    # 计算总体均值
    grand_mean = np.mean(data)

    # 计算每个样本的观察值和样本大小
    sample_means = np.mean(data, axis=1)
    sample_sizes = data.shape[1]

    # 计算每个样本的平方和
    ss_total = np.sum((data - grand_mean)**2)

    # 计算组内平方和
    ss_within = np.sum((data - sample_means[:, np.newaxis])**2)

    # 计算组间平方和
    ss_between = ss_total - ss_within

    # 计算自由度
    df_between = data.shape[0] - 1
    df_within = data.shape[0] * (sample_sizes - 1)

    # 计算卡方统计量
    chi2_statistic = (ss_between / df_between) / (ss_within / df_within)

    # 计算临界值
    critical_value = chi2.ppf(1 - alpha, df_between)

    # 判断是否拒绝原假设
    result = chi2_statistic > critical_value

    return result


卡方检验结果:
卡方统计量: 0.5555555555555556
p值: 0.7574651283969664
